import Sidebar from "@/components/Sidebar";
import "../../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardRootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <div className="flex">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
