import NavbarDashboard from "@/components/DashboardPages/NavbarDashboard/NavbarDashboard";
import "../../globals.css";
import HomeDashboard from "@/components/DashboardPages/HomeDashboard/HomeDashboard";
import SidebarDashboard from "@/components/DashboardPages/SidebarDashboard/SidebarDashboard";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardRootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <div className="flex">
          <NavbarDashboard />
          <SidebarDashboard />
          {children}
        </div>
      </body>
    </html>
  );
}
